# Generated by Django 4.1.3 on 2022-11-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no2', models.FloatField()),
                ('co2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('start_timestamp', models.TimeField(auto_now_add=True)),
                ('cell_edge', models.IntegerField()),
                ('min_samples', models.IntegerField()),
                ('sampling_period', models.IntegerField()),
                ('planning_limit_time', models.IntegerField()),
                ('campaign_duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inferior_coord', models.CharField(max_length=100)),
                ('superior_coord', models.CharField(max_length=100)),
                ('center', models.CharField(max_length=100)),
                ('cell_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CellMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TimeField()),
                ('measurement_type', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('airdata_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSocioBee.airdata')),
                ('cell_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSocioBee.cell')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='QueenBee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.SmallIntegerField()),
                ('send', models.SmallIntegerField()),
                ('open', models.SmallIntegerField()),
                ('acepted', models.SmallIntegerField()),
                ('planning', models.SmallIntegerField()),
                ('realized', models.SmallIntegerField()),
                ('timestamp_update', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Surface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSocioBee.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('cell_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSocioBee.cell')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_timestamp', models.TimeField()),
                ('planning_timestamp', models.TimeField()),
                ('cellMeasurement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSocioBee.cellmeasurement')),
                ('cell_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSocioBee.cell')),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSocioBee.participant')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSocioBee.state')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementPromise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_send', models.TimeField()),
                ('promise_timestamp', models.TimeField()),
                ('cellMeasurement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSocioBee.cellmeasurement')),
                ('cell_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSocioBee.cell')),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSocioBee.participant')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSocioBee.state')),
            ],
        ),
        migrations.CreateModel(
            name='CellPriority',
            fields=[
                ('timestamp', models.TimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('temporal_priority', models.FloatField()),
                ('trend_priority', models.FloatField()),
                ('cellprioritycol', models.CharField(max_length=45)),
                ('slot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSocioBee.slot')),
            ],
        ),
        migrations.AddField(
            model_name='cellmeasurement',
            name='participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSocioBee.participant'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='queenBee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSocioBee.queenbee'),
        ),
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundary', models.CharField(max_length=100)),
                ('surface_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSocioBee.surface')),
            ],
        ),
    ]
